language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "robinhowlett-github"
    token:
      secure: "$SONARCLOUD_TOKEN"
jdk: oraclejdk8
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/A6QERQ0AD
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy scm:tag -Dpassword=$GITHUB_TOKEN -Drevision=$TRAVIS_BUILD_NUMBER"
  skip_cleanup: true