language: java
sudo: false
jdk: oraclejdk8
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/A6QERQ0AD
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
addons:
  sonarcloud:
    organization: "robinhowlett-github"
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install:
  - mvn install -P !build-extras -DskipTests=true -B -V
script:
  - mvn clean test -P !build-extras -B
after_success:
  - ./.travis.before-deploy.sh
deploy:
  provider: script
  script: "mvn deploy -P sign,build-extras --settings .travis.settings.xml"
  skip_cleanup: true
  on:
    tags: true
