language: java
jdk: oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/A6QERQ0AD
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy scm:tag -Drevision=$TRAVIS_BUILD_NUMBER"