language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "robinhowlett-github"
    token:
      secure: "$SONAR_TOKEN"
jdk: oraclejdk8
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/A6QERQ0AD
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
script:
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -P !build-extras -B
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install:
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - ./.travis.before-deploy.sh
  - ./.travis.deploy.sh
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy scm:tag -Dpassword=$GITHUB_TOKEN -Drevision=$TRAVIS_BUILD_NUMBER"
  skip_cleanup: true
