language: java
sudo: false
jdk: oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/A6QERQ0AD
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
addons:
  sonarcloud:
    organization: "robinhowlett-github"
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install:
  - mvn install -P !build-extras -DskipTests=true -B -V
script:
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -P !build-extras -B
after_success:
  - openssl aes-256-cbc -K $encrypted_6c0a552ded21_key -iv $encrypted_6c0a552ded21_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --fast-import codesigning.asc
deploy:
  provider: script
  script: "mvn deploy -P sign,build-extras --settings .travis.settings.xml"
  skip_cleanup: true
  on:
    tags: true
